listen: 0.0.0.0:9000
api-url: http://api.tokenlon.im

tezos:
    mysql: root:WcGsHDMBmcv7mc#QWkuR@tcp(127.0.0.1:3306)/tezos_index?charset=utf8mb4&parseTime=True&loc=Local
    redis: redis://127.0.0.1:6379/1
#    chain: http://127.0.0.1:8732
    chain: https://mainnet-tezos.giganode.io
#    proxy: http://127.0.0.1:8001 # optional
    network: mainnet
    port: 9000
